---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: latex_cv.tex
geometry: margin=1in

title: "CV"
author: Daniel J. Hocking

jobtitle: "Statistician, NOAA-Fisheries"
address: "GARFO Monitoring and Analysis Section · 55 Great Republic Drive · Gloucester, MA 01930"
fontawesome: yes
email: daniel.hocking@noaa.gov
github: djhocking
phone: "978-281-9324"
web: hockinglab.weebly.com

keywords: teaching, academic CV, research

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

I am a United States Citizen and registered for Selective Service.

# Professional Experience

**Statistician**, Greater Atlantic Regional Fisheries Office, National Marine Fisheries Service, NOAA. 06/08/20 - present. 40 hrs/wk. ZP-03

*Duties:* Provide partner-driven analyses in support of marine fisheries monitoring, sustainable harvest, and protected resources. Serve as the lead programmer for the Catch Accounting and Monitoring System (CAMS) to integrate all fisheries dependent data sources from the Greater Atlantic Region (North Carolina to Maine) to create one set of official records for all users at the regional office and science center ([http://nerswind/cams/](http://nerswind/cams/) - available on NOAA intranet only). Develop innovative analytical solutions to meet organizational needs and generate products for internal and external partners with specific deadlines. Work with various partners and stakeholders as the authoritative source of fisheries data science to meet needs and advise on management, policy, and data life cycle decisions. Lead the development and integration of best data science practices including semantic version control of software with GitHub actions for continuous integration, automated Oracle table and view creation, Apache Arrow use for speed and out-of-memory computation when needed, and literate programming for automated, reproducible reports, websites, and interactive intranet applications. Develop guides for other programmers to ensure consistent programming style and structure, news updates, and version control to ensure protection of the main production branch during development. Other regular duties include catch accounting, monitoring, and forecasting of squid, mackerel, and butterfish catch to ensure fisheries closures when needed with adequate time for fleet notification and publication in the Federal Registry and collaborate with team members to support marine ecosystem data requests.


**Assistant Professor**, Dept. of Biology, Frostburg State University. 08/25/16 - 06/07/20. 40 hrs/wk.

*Duties:* Taught 15-21 in-class contact hours per semester including Quantitative Population Analysis (BIOL 414/514), General Ecology (BIOL 340), Herpetology (BIOL 422/522), Zoology Laboratory (BIOL 160), Special Topics in Biology (BIOL 499), and Graduate Research Methods (BIOL 600). Advised 30 undergraduate fish and wildlife students. Mentored graduate students and coordinated a research program focused on statistical ecology of fish and wildlife populations. Identified sources of funding and wrote grants to support student research. Supervised graduate and undergraduate research projects and the development of reproducible code with quality assurance for data processing analyses. Presented findings at scientific meetings and in peer-reviewed publications. Projects included assessing the function of spatial and temporal replication to detect changes in fish populations, coordinating regional data integration and modeling of stream salamander distributions, and developing a Bayesian Spatial Capture-Recapture model of aquatic turtles in the C&O Canal National Historical Park. Other duties included service to the department, university, profession, and community.

**USGS Mendenhall Postdoctoral Fellow**, Research Ecologist, Conte Anadromous Fish Research Laboratory, Leetown Science Center. GS-12. 06/29/14 - 08/15/16. 40 hrs/wk. GS-12

*Duties:* Conducted multiple complex research projects to support natural resource management decisions for freshwater fish and stream ecosystems. Helped coordinate a regional stream temperature network including more than 20 state and federal agencies, researchers, and NGOs to establish standardized protocols, a central SQL database, and a system of quality control and quality assurance. Developed Bayesian statistical models for daily stream temperature and fish occupancy across the northeastern US and contributed to the implementation of an interactive visualization of the data and model results (http://ice.ecosheds.org/). Formulated a novel geostatistical model of stream fish densities using Template Model Builder (TMB) implemented through the R programming language. Ensured reproducibility and automation using bash scripts and documented in a public GitHub repository.

**Postdoctoral Fellow**, DOI Northeast Climate Science Center. University of Massachusetts. 01/15/13 - 06/28/14. 40 hrs/wk.

*Duties:* Gathered regional stream data from state and federal partners from Virginia to Maine. Programmatically parsed data from diverse sources to ensure reliability and reproducibility in creation of an SQL database. Developed statistical models to assess climate change effects on stream temperature and stream vertebrate (fish and salamander) populations. Participated in a Structured Decision Making process to facilitate stream management actions across jurisdictional boundaries. Worked with stakeholders to clarify objectives related to management goals and determine data and analysis needs to evaluate alternative actions. Coordinated and helped design expert elicitation to develop and test statistical models based on the best available knowledge.

**Postdoctoral Research Associate**, University of New Hampshire. 05/25/12 - 01/01/13. 40 hrs/wk.

*Duties:* Assessed populations in response to land-use and environmental change using both marked and unmarked methods. Designed and conducted experiment to assess spatial variation in the role of vertebrate density on ecosystem functions. Supervised diverse teams of undergraduates and technicians on field and laboratory projects. Wrote grants to fund research projects. Wrote and administered Animal Use Protocol approved by the IACUC and secured state and federal permits to ensure appropriate and ethical use of animals in research. Designed and conducted field research to assess distributions of salamanders over an elevational gradient in Great Smoky Mountains National Park. Analyzed results, presented at national and international conferences, and published in scientific, peer-reviewed journals.

# Education

2012 \hspace{4mm} PhD Natural Resources & Environmental Studies, University of New Hampshire  

2007 \hspace{4mm} MA Biological Sciences, University of Missouri

2003 \hspace{4mm} BS Environmental Science, University of New Hampshire

# Publications

[Google Scholar](https://scholar.google.com/citations?user=qIFCelIAAAAJ)
(citations = 1421, *h*-index = 19, *i*10-index = 23)  
\*\*undergraduate, \*graduate student, <sup>+</sup>postdoc

<!--
Brooks, J.L.\*, A.B. Brand, E.H. Campbell Grant, and **D.J. Hocking**. *In Preparation*. Stream-breeding salamander occupancy across the Mid-Atlantic region of the United States. [[Code](https://github.com/jclbrooks/MD_Stream_Salamanders/tree/master/Code)]

Katz R.A., E. Grant, A. Roy, M. Runge, **D.J. Hocking**, B. Letcher. In Preparation. Challenges facing Collaborative Landscape Conservation: A Decision Analytic Perspective. To be submitted to Frontiers in Ecology and the Environment.

Katz R.A., E. Grant, **D.J. Hocking**, W. Fields, A. Brand, et al. In Preparation. Predicting stream salamander occurrence when data is lacking using expert opinion. To be submitted to Diversity and Distributions.
-->

**Hocking, D.J.**, K. O'Neil, J. Walker, and B.H. Letcher. *In Revision*. A hierarchical model of daily stream temperature for regional predictions. [[Code](https://github.com/Conte-Ecology/conteStreamTemperature_northeast), [Data](http://db.ecosheds.org/), [Preprint](https://github.com/Conte-Ecology/conteStreamTemperature_northeast/blob/master/manuscripts/northeast_temperature_ms.pdf),
[Interactive Visualization](http://ice.ecosheds.org/)]

Salois, S.L., , K.J.W. Hyde, A. Silver, A. Gangopadhyay, G. Gawarkiewicz, A.M. Mercer, B.A. Lowman, J.P. Manderson, S.K. Gaichas, **D.J. Hocking**, B. Galuardi, A.W. Jones, J. Kaelin, G. DiDomenico, K. Almeida, B. Bright, M. Lapp. 2023. Shelf break exchange processes influence the availability of the Northern Shortfin Squid, <i>Illex illecebrosus</i>, in the Northwest Atlantic. Fisheries Oceanography. 32(5):461-478 [https://doi.org/10.1111/fog.12640](https://doi.org/10.1111/fog.12640)

N.T. Haydt\*, S.C. Sterrett, and **D.J. Hocking**. 2022. Aquatic turtle densities and home ranges estimated using spatial capture-recapture. Journal of Herpetology. 56(2):203-210. [[Code](https://github.com/djhocking/co_canal_turtles)

Earl, J.E., S.M. Blomquist, E.B. Harper, **D.J. Hocking**, M.L. Hunter, J.R. Johnson, M.S. Osbourn, D.A Patrick, V.D. Popescu, T.A.G. Rittenhouse, and B.B. Rothermel. 2022. Amphibian biomass export from geographically isolated wetlands: Temporal variability, species composition, and potential implications for terrestrial ecosystems. Diversity. 14(3)163:1-17. [https://doi.org/10.3390/d14030163](https://doi.org/10.3390/d14030163)

Anderson, L.T., J.E. Earl, **D.J. Hocking**, M.S. Osbourn, and T.A.G. Rittenhouse. 2021. Demographic impacts of phenological variation in natural populations of two pond-breeding salamanders. Oecologia. 196(4):1073-1083. [https://doi.org/10.1007/s00442-021-05000-y](https://doi.org/10.1007/s00442-021-05000-y)

**Hocking, D.J.**, J.A. Crawford, W.E. Peterman, and J.R. Milanovich. 2021. Abundance of Montane Salamanders Over an Elevational Gradient. Ecology and Evolution. 11(3):1378-1391.  [https://doi.org/10.1002/ece3.7142](https://doi.org/10.1002/ece3.7142)

Gade, M.R.\*, G.M. Connette, J.A. Crawford, **D.J. Hocking**, J.C. Maerz, J.M. Milanovich, and W.E. Peterman. 2020. Predicted alteration of terrestrial salamander surface activity as a consequence of climate change. 101(11): e03154 [https://doi.org/10.1002/ecy.3154](https://doi.org/10.1002/ecy.3154)

Pregler, K.C.\*, R.D. Hanks<sup>+</sup>, E. Childress, N.P. Hitt, **D.J. Hocking**, B.H. Letcher, T. Wagner, and Y. Kanno. 2019. State-space analysis of power to detect regional brook trout population trends over time. Canadian Journal of Fisheries and Aquatic Sciences. 76(11): 2145-2155.

Sterrett, S.C., R.A. Katz, A.B. Brand, W.R. Fields, A.E. Dietrich, **D.J. Hocking**, T.M. Foreman, A.N.M. Wiewel, E.H. Campbell Grant. 2019. Proactive management of amphibians: Challenges and opportunities. Biological Conservation. 236: 404-410.

**Hocking, D.J.**, J. Thorson, K. O'Neil, and B.H. Letcher. 2018. A geostatistical state-space model of animal abundance for stream networks. Ecological Applications. 28: 1782-1796. [https://doi.org/10.1002/eap.1767](https://doi.org/10.1002/eap.1767). [[Code](https://github.com/djhocking/Trout_GRF), 
[Data](https://github.com/djhocking/Trout_GRF/tree/master/Data)]]

Earl, J.E., E.B. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, M. Glennie, and R.D. Semlitsch. 2017. Relative importance of timber harvest and habitat for reptiles in experimental forestry plots. Forest Ecology and Management. 402: 21-28. [https://doi.org/10.1016/j.foreco.2017.07.014](https://doi.org/10.1016/j.foreco.2017.07.014)

Stephens, R.B.\*, **D.J. Hocking**, M. Yamasaki, and R.J. Rowe. 2017. Synchrony in small mammal community dynamics across a forested landscape. Ecography. 40: 1198–1209. [http://dx.doi.org/10.1111/ecog.02233](http://dx.doi.org/10.1111/ecog.02233). [[Data](http://datadryad.org/resource/doi:10.5061/dryad.76jr5)]

Buckman, K., V. Taylor, H. Broadley, **D.J. Hocking**, P. Balcom, R. Mason, K. Nislow, and C. Chen. 2017. Landscape influences on methylmercury bioaccumulation in an urban estuary: Delaware River, USA. Estuaries and Coasts. 40(5):1358–1370. [https://dx.doi.org/10.1007%2Fs12237-017-0232-3](https://dx.doi.org/10.1007%2Fs12237-017-0232-3)

Earl, J.E., E. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, and R.D. Semlitsch. 2016. Effects of timber harvest on small mammal captures in experimental forestry plots. Animal Biology. 66:347 – 362. [http://dx.doi.org/10.1163/15707563-00002511](http://dx.doi.org/10.1163/15707563-00002511)

Letcher, B.H., **D.J. Hocking**, K. O'Neil, A.R. Whiteley, K.H. Nislow, and M.J. O'Donnell. 2016. A hierarchical model of daily stream temperature using air-water temperature synchronization, autocorrelation, and time lags. PeerJ. 4:e1727 [https://doi.org/10.7717/peerj.1727](https://doi.org/10.7717/peerj.1727)

Peterman, W.E., J.A. Crawford, and **D.J. Hocking**. 2016. Effects of elevation on plethodontid salamander body size. Copeia. 104(1):202-208. [http://dx.doi.org/10.1643/OT-14-188](http://dx.doi.org/10.1643/OT-14-188)

Milanovich, J.R., **D.J. Hocking**, W.E. Peterman, and J.A. Crawford. 2016. Effective use of trails for assessing terrestrial salamander abundance and detection:  A case study at Great Smoky Mountains National Park. Natural Areas Journal. 35(4):590-598. [http://dx.doi.org/10.3375/043.035.0412](http://dx.doi.org/10.3375/043.035.0412)

Anderson, T.L., **D.J. Hocking**, C.A. Conner, J.E. Earl, E.B. Harper, M.S. Osbourn, W.E. Peterman, T.A.G. Rittenhouse, and R.D. Semlitsch. 2015. Abundance and phenology patterns of two pond-breeding salamanders determine species interactions in natural populations. Oecologia. 177(3):761-73. [http://dx.doi.org/10.1007/s00442-014-3151-z](http://dx.doi.org/10.1007/s00442-014-3151-z)

Drake, D.L, B.H. Ousterhout, C.D. Shulse, **D.J. Hocking**, W.E. Peterman, T.A. Anderson, K.L. Lohraff, C.A. Conner, E.H. Harper, J.R. Johnson, T.A.G. Rittenhouse, B.B. Rothermel, L.S. Eggert, and R.D. Semlitsch. 2015. Pond-breeding amphibian community composition in Missouri. American Midland Naturalist. 174:180-187.

**Hocking, D.J.** and K.J. Babbitt. 2014. Amphibian Contributions to Ecosystem Services. Herpetological Conservation and Biology. 9(1):1-17. [**OA**]

**Hocking, D.J.** and K.J. Babbitt. 2014. The role of red-backed salamanders on ecosystem functions. PLoS ONE 9(1):e86854. [http://dx.doi.org/10.1371/journal.pone.0086854](http://dx.doi.org/10.1371/journal.pone.0086854) [**OA**]

**Hocking, D.J.** 2013. Comparing the influence of ecology journals using citation metrics: making sense of a multitude of metrics. Ideas in Ecology & Evolution. 6(1): 55–65. [http://dx.doi.org/10.4033/iee.v6i1.4949](http://dx.doi.org/10.4033/iee.v6i1.4949) [**OA**]

**Hocking, D.J.**, S.A. Callaghan, K.J. Babbitt, and M. Yamasaki. 2013. Comparison of silvicultural and natural disturbance effects on terrestrial salamanders in northern hardwood forests. Biological Conservation. 167:194-202. [http://dx.doi.org/10.1016/j.biocon.2013.08.006](http://dx.doi.org/10.1016/j.biocon.2013.08.006)

**Hocking, D.J.**, G.M. Connette, C.A. Conner, B.R. Scheffers, S.E. Pittman, W.E. Peterman, R.D. Semlitsch. 2013. Effects of experimental forest management on a terrestrial, woodland salamander in Missouri. Forest Ecology and Management. 287:32-39

Osbourn, M.S., **D.J. Hocking**, C.A. Conner, W.E. Peterman, and R.D. Semlitsch. 2011. Use of fluorescent visible implant Alphanumeric tags to individually mark juvenile ambystomatid salamanders. Herpetological Review 42(1):43-46.

**Hocking, D.J.** 2010. *Hyla squirella* (squirrel treefrog) reproduction. Herpetological Review 41(1):64.

Semlitsch, R.D., S.M. Blomquist, A.J.K. Calhoun, J.W. Gibbons, J.P. Gibbs, G.J. Graeter, E.B. Harper, **D.J. Hocking**, M.L. Hunter, D.A. Patrick, T.A.G. Rittenhouse, B.B. Rothermel, and B.D. Todd. 2009. Effects of timber management on amphibian populations: understanding mechanisms from forest experiments. Bioscience 59(10):853-862. (Cover Photograph)

Scheffers, B., E.D. McDonald, **D.J. Hocking**, C.A. Conner, and R.D. Semlitsch. 2009. A comparison of two artificial cover objects for sampling amphibians and reptiles. Herpetological Review 40(4):419-421.

Babbitt K.J., M.J. Baber, D.L. Childers, and **D.J. Hocking**. 2009. The influence of agricultural upland habitat type on larval anuran assemblages in seasonally-inundated wetlands. Wetlands 29(1):294-301.

**Hocking, D.J.** and R.D. Semlitsch. 2008. Effects of clearcut logging on gray treefrog (Hyla versicolor) tadpole performance. Journal of Herpetology 42:689-698.

**Hocking, D.J.**, T.A.G. Rittenhouse, B.B. Rothermel, J.R. Johnson, C.A. Conner, E.B. Harper, and R.D. Semlitsch. 2008. Breeding and recruitment phenology of amphibians in Missouri oak-hickory forests. American Midland Naturalist 160:41-60.

Semlitsch, R.D., C.A. Conner, **D.J. Hocking**, T.A.G. Rittenhouse, and E.B. Harper. 2008. Effects of timber harvesting on pond-breeding amphibian persistence: testing the evacuation hypothesis. Ecological Applications 18(2):283-289.

**Hocking, D.J.** and R.D. Semlitsch. 2007. Effects of timber harvest on breeding site selection by gray treefrogs (Hyla versicolor). Biological Conservation 138:506-513.

## White Papers

West Virginia Division of Natural Resources. *In review*. Cheat Mountain salamander (*Plethodon nettingi*) population monitoring plan. pp 1-33.

Katz, R., E.H.C. Grant, M.C. Runge, B. Connery, M. Crockett, L. Herland, S. Johnson, D. Kirk, J. Wofford, R. Bennett, K. Nislow, M. Norris, **D.J. Hocking**, B.H. Letcher, A. Roy. 2014. Making decisions in complex landscapes: Headwater stream management across multiple federal agencies. US Geological Survey Whitepaper. Report to the DOI Northeast Climate Science Center. [https://pubs.er.usgs.gov/publication/70193846](https://pubs.er.usgs.gov/publication/70193846)

## Non-Peer Reviewed

**Hocking, D.J.** 2019. Book Review: The Maryland Amphibian and Reptile Atlas. Eds. H.R. Cunningham and N.H. Nazdrowicz. Herpetological Review. 50(4): 828-829. 

# Software

Chamberlain, S., **D.J. Hocking**, B. Anderson, M. Salmon, A. Erickson, N. Potter, J. Stachelek, A. Simmons, K. Ram, and H. Edmund. 2020 - present. rnoaa: 'NOAA' Weather Data from R. R package version 1.3.8. [https://github.com/ropensci/rnoaa](https://github.com/ropensci/rnoaa). Soon to be deprecated due to API change.

**Hocking, D.J.**, J.M. Lanning, B. Galuardi, D. Linden, K. Winiarski, and B. McAfee. 2021 - present. MAPS: Monitoring Analysis Program System for implementing the Catch Accounting and Monitoring System. *Internal NOAA Only*. [https://github.com/noaa-garfo/MAPS](https://github.com/noaa-garfo/MAPS)

Smith, L.G., **D.J. Hocking**, and N. Nagle. 2020 - present. pcrecon: Principal component regression for tree ring data. [https://github.com/lgsmith295/pcrecon](https://github.com/lgsmith295/pcrecon)

**Hocking, D.J.** and L.G. Smith. 2020. dendro_bayes: Testing Bayesian climate modeling with hierarchical standardization. Code: [https://github.com/lgsmith295/dendro_bayes](https://github.com/lgsmith295/dendro_bayes), Example Use: [https://lgsmith295.github.io/dendro_bayes/](https://lgsmith295.github.io/dendro_bayes/)

**Hocking, D.J.** *In Prep*. noaaWeather: NOAA weather data from R for a new API.

**Hocking, D.J.** *In Prep*. rfoss: NOAA Fisheries data in R from the Fisheries One Stop Shop API.

# Grants 

<!--
## In Review
-->

## Awarded (Total: $651,057)

NOAA Office of Sustainable Fisheries MSA Implementation Improvement. Improving Management of Northern Shortfin Squid, <i>Illex illecebrosus</i> by Understanding Oceanographic & Ecosystem Drivers.  K. Hyde, D.J. Hocking, J. Didden, and A. Mercer. 2023. $206,225

National Park Service. Survey of amphibian population and disease in the Western C&O Canal National Historical Park. 2020. $35,000. *Declined and not included in award total*

MD Department of Natural Resources - Heritage Program. Construction and establishment of hellbender nestboxes in Maryland. D.J. Hocking. 2020. $16,233.

National Park Service. Natural Resource Stewardship and Science FY19 Servicewide Comprehensive Call. Effects of wildfire on salamander populations in Great Smoky Mountains National Park. W.E. Peterman, D.J. Hocking, J.A. Crawford, and J.R. Milanovich. 2019. $76,464.

Appalachian Highlands Science Learning Center Research Grants. Effects of wildfire on salamander populations in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, and J.R. Milanovich. 2019. $2,000.

Frostburg Foundation Opportunity Grant. Effects of acid mine drainage and stream restoration on Plethodontid salamanders. D.J. Hocking and J. Brooks\*. 2018. $1,329. 

Frostburg State University. Faculty Development Graduate Research Grant. Spatial patterns, home ranges, and associated parasites in the Chesapeake and Ohio Canal National Historic Park. D.J. Hocking and N. Haydt\*. 2018. $1,500.

Appalachian Highlands Science Learning Center Research Grants. Short-term effects of wildfire on salamander populations in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, and J.R. Milanovich. 2018. $2,000

Great Smoky Mountains Conservation Association. Carlos C. Campbell and James T. Tanner Memorial Fund. Short-term Effects of Wildlife on Salamander Populations in Great Moky Mountains National Park. D.J. Hocking, J.A. Crawford, W.E. Peterman, J.R. Milanovich. 2017. $5,000

Appalachian Highlands Science Learning Center Research Grants. Short-term effects of wildfire on salamander populations in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, J.R. Milanovich. 2017. $1,124

Frostburg State University. Faculty Development Undergraduate Research Grant. D.J. Hocking. 2017. $3,750.

Frostburg State University CLAS Strategic Plan Fund. Salamander population and adaptation research collaborative network. D.J. Hocking. 2017. $500

USGS Mendenhall Research Fellowship. Hierarchical modeling of climate change effects: Land-use impacts on brook trout population persistence. D.J. Hocking. 2014-2016. $250,000

National Geographic Society. Waitt Grant. Climate change effects on elevational distributions of salamanders in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, J. Milanovich, W.E. Peterman. 2012. $14,932
 
NH Agricultural Experiment Station. McIntire-Stennis. The role of red-backed salamanders (*Plethodon cinereus*) in forest-floor ecosystem functions. D.J. Hocking, K.J. Babbitt. 2011. $42,000

University of New Hampshire. Dissertation Year Fellowship. The contributions of woodland salamanders to ecosystem functions. D.J. Hocking. 2011. $16,000

University of Missouri. Trans-World Airlines Scholarship. The effects of predators on gray treefrog (*Hyla versicolor*) growth, survival, and development. D.J. Hocking. 2006. $7,000

<!---
## Not Awarded

Herpetologists League, Raymond Semlitsch Memorial Award. The Effects of Reduced Snowpack on Woodland Salamander Populations. 2019. $5,000

Natalie - Frostburg Foundation

Jacey - FSU

FWS oiled turtles

SERDEP

-->

# Awards

Employee of the Year. 2023. Greater Atlantic Regional Fisheries Office. National Oceanic and Atmospheric Administration. US Department of Commerce.

College Outstanding Achievements in Research. 2020. Frostburg State University. College of Liberal Arts and Science. 

Meritorious Award for Research. 2018. Frostburg State University. College of Liberal Arts and Science.


# Teaching

## Courses

* General Ecology (BIOL 340), Frostburg State University. 2016 - 2020. Spring, Fall.

* Herpetology (BIOL 422/522), Frostburg State University. 2017 - 2020. Spring.

* Quantitative Analysis of Vertebrate Populations (BIOL 414/514). 2017 - 2020. Fall.

* General Zoology Laboratory (BIOL 160), Frostburg State University. 2016 - 2019. Variable.

* Graduate Research Methods (BIOL 600), Frostburg State University. 2019.

* Special Problems in Biology (BIOL 499), Frostburg State University. 2018 - 2020. Variable.

* Vertebrate Biology (NR 655), University of New Hampshire. 2009.

* Introduction to Conservation Biology (BIO 105), Moberly Area Community College, Columbia, MO. 2007.

## Teaching Assistant

* Wildlife Techniques (NR 646), University of New Hampshire. 2007, 2009.

* Conservation Biology (NR 650), University of New Hampshire. 2008.

## Tutor

* Introductory Biology (Bio 412), University of New Hampshire. 2010.

* Freshwater Resources (NR 504), University of New Hampshire. 2010.

* Sociology Statistics (Soc 502), University of New Hampshire. 2008-2010.

* Contemporary Conservation Issues (NR 435), University of New Hampshire. 2009.

## Environmental Education

* Senior Environmental Intern. Audubon Maryland-DC. 2003-2004.

* Seasonal Naturalist. NH Seacoast Science Center. 2001-2003.

## Certifications

* Cognate in College Teaching, Center for Excellence in Teaching & Learning, University of New Hampshire

* Software Carpentry Instructor, Teaching Lab Skills for Scientific Computing [http://software-carpentry.org/](http://software-carpentry.org/) 

# Research Mentoring

## Graduate Students

<!--
* Emily Phillips. Terrestrial salamander densities and population dynamics. 2019.
-->

* Natalie Haydt. Spatial capture-recapture and disease of turtles along a depth gradient in the C&O Canal. 2017 - 2019

* Jacey Brooks. The effects of acid mine drainage and remediation on stream salamander populations. 2017 - 2019

* Bethany Liberto. Abundance and distribution of rare dragonflies in high elevation bogs. *Co-advised with Dr. Jered Studinski*. 2017 - 2019

## Graduate Student Committees

Ryan Stephens (PhD, University of New Hampshire, 2018); Elizabeth Green (MS, Frostburg State University, 2019); Sabrina Edwards (MS, Frostburg State University); Emily Harlan (MS, Frostburg State University); Erica Duda (MS, Frostburg State University, 2019); Stephen Knott (MS, Frostburg State University, 2022)

## Undergraduate Researchers

I have mentored 14 undergraduate students (6 women, 8 men) on independent research projects, including multiple first generation college students, one U.S. Marine Veteran, and one U.S. Army Veteran. 

<!---

Allison Williams. 2019-2020. Salamander spatial capture-recapture for population assessment. Hellbender nestbox contruction and surveys.

Kodi Bowers. 2019-2020. Snorkel and nestbox surveys of the state-endangered Hellbender (*Cryptobranchus alleganiensis*).

Feodora Offei. 2019. Salamander populations and adaptations: A mark-recapture study.

Shelbi Sullivan. 2019. Red-backed salamander (*Plethodon cinereus*) population dynamics.

Jason Saffer. 2019. Models for assessing fish populations from count data.

Justin Hansen. 2017-2018. Collection and curation for an amphibian and reptile teaching collection.

John Garrison - spotted turtles

Brady Moon. 2018. Abundance and distribution of terrestrial salamanders in a Maryland Forest.

Patrick - hematology 

Janine Appleton - hematology

Tessa Corsetti - The effects of habitat type of salamander ecosystem functions.

Rachel Mahan - treefrogs

Barlows, A.\*\*, D. J. Hocking, and R. D. Semlitsch.  Effects of shade and predation on survival and growth of larval gray treefrogs (*Hyla versicolor*) in Missouri.  2006 University of Missouri-Columbia Undergraduate Research and Creative Achievements Forum.  

Mahan, R. D.\*\*, B. B. Rothermel, D. J. Hocking, J. W. Gibbons, and R. D. Semlitsch. Effects of forest management practices on treefrog oviposition site choice. 2005

Sargent, P. J.\*\*, D. J. Hocking, K. J. Babbitt. Relating Hematological Patterns in Red-backed Salamanders to Stress in Different Habitats and Densities. 2013. Undergraduate Research Conference, UNH, Durham, NH.

Marquis, A. J.Landscape and local-scale effects on stream salamanders in southeastern New Hampshire. 2012. 

Willey, E.\*\*, D. J. Hocking, K. J. Babbitt. The effects of forest fragmentation on the abundance and body condition of the red backed salamander (*Plethodon cinereus*)

-->

# Professional and Community Service

## Manuscript Reviewing

**Associate Editor**: Conservation Science and Practice, Societ of Conservation Biology. 2023 - present

**Articles Reviewed For**: AMBIO, Bioscience, Conservation Biology, Copeia, Ecological Applications, Ecology and Evolution, Ecosphere, Fisheries Research, Forest Ecology and Management, Freshwater Biology, Global Change Biology, Herpetological Conservation and Biology, Herpetological Review, Journal of Herpetology, Journal of Wildlife Management, Northeastern Naturalist, Oikos, PeerJ, PLoS ONE, Urban Ecosystems, Wetlands

## University Service

* Faculty Senate Ad-Hoc Committee on Evaluations II. 2018-2020.

* President's Advisory Council on Sustainability (PACS). 2018-2020.

* Faculty Appeals Committee. 2019-present

## College Service

* CLAS Faculty Awards Committee. 2019-2020.

## Department Service

* Wildlife and Fisheries and Interpretive Biology and Natural History Curriculum Committee. 2017-2020.

* The Wildlife Society, Frostburg State University Chapter. Faculty Advisor. 2017-2020.

* Campus Tree Committee, Frostburg State University. 2016-2019.

* R Programming and Statistical Users Group, Faculty Advisor, Frostburg State University. 2017-2019. 

* Hiring committee. Full-Time, Non-Tenure Track Faculty to teach Introductory Biology, Zoology, and Anatomy and Physiology. 2018.

* Department Evaluation Committee, Biology Department, Frostburg State University. 2016-2017.

## General

* Working Group. Cheat Mountain Salamander Endangered Species Act Recovery Monitoring. 2019 - 2020.

* Outreach. Led a field trip for high school students to learn about salamander ecology. Purchase Knob, Great Smoky Mountains National Park. 26 June 2019.

* Interviewed for articles in [*Discover*](http://discovermagazine.com/2018/jul-aug/the-salamander-army) magazine and [*Mongabay.com*](https://news.mongabay.com/2018/12/essential-ubiquity-how-one-tiny-salamander-species-has-a-huge-impact/). 2018.

* Organizing Committee. Northeastern Stream Temperature Monitoring and Analysis Meeting. US Fish and Wildlife Service. Region 5 Regional Office. Hadley, MA. 21-22 February 2017.

* Cofounded the New Hampshire R Users Group, including organizing weekly meetings and securing corporate sponsorship. 2013 – 2014.

* Organizer. NRESS Seminar. University of New Hampshire. Helped organize the spring seminar series for the Natural Resource and Earth System Science program. 2008.

* Vice President. Biology Graduate Student Association. University of Missouri. 2005-2006.

* Webmaster. Land-use Effects on Amphibian Populations (LEAP) Collaboration. 2004-2005.

* Webmaster. Missouri Chapter of the Society for Conservation Biology. 2005-2006.

* Co-Chair. Outreach Committee for the Missouri Chapter of the Society for Conservation Biology. 2005-2006.

## Outreach

* Taxonomic Expert. Gulf of Maine Research Institute, Vital Signs citizen science program. 2014 – 2019.

* Guest Speaker. Great Smoky Mountain Institute at Tremont, GSMNP, NC. July 2012. Talked to a science camp group about salamander biodiversity in Great Smoky Mountains National Park.

* Guest Speaker. Traip Academy, Kittery, ME. May 2011. Discussed college programs in math and science and career paths in ecology and conservation with high school seniors.

* Guest Speaker. Hickman Highschool Biology Club. October 2006. Amphibians, reptiles, and college planning for aspiring biologists.

* BioBlitz Organizer and Team Leader. Columbia, MO. 2005-2006.

# Presentations

\*\*undergraduate, \*graduate student, <sup>+</sup>postdoc

## Oral Presentations

Williams, A.K.\*\* and D.J. Hocking. Spatial and Temporal Variability in Salamander Population Size. The Wildlife Society Annual Meeting. October 2020.

Hocking, D.J. *Invited Seminar*: Models and Visualization of Regional Stream Temperature and Trout Populations. University of Maryland Center for Environmental Science. Appalachian Laboratory. 11 May 2017.

Hocking, D.J. Climate effects on brook trout populations. NECSC Colloquium Webinar. DOI Northeast Climate Science Center, University of Massachusetts-Amherst. [https://necsc.umass.edu/webinars/early-career-showcase](https://necsc.umass.edu/webinars/early-career-showcase). 23 March 2016.

Hocking, D. J., B. Letcher, K. Nislow, Y. Kanno, M. Ratnaswamy, and J. Wofford. Using single-pass surveys to assess spatial and temporal patterns in Brook Trout abundance: Correcting for imperfect detection. American Fisheries Society Annual Meeting, Quebec City, Canada. 17-21 August 2014.

Hocking, D. J. *Invited Seminar*: The effects of land-use and climate change on amphibian populations. Environmental Science Seminar Series. University of New Hampshire, Durham, NH. 11 October 2013.

Hocking, D. J. and K. J. Babbitt. Comparisons of models for analyzing seasonal activity using longitudinal count data. Ecological Society of America Annual Meeting, Portland, OR.4-10 August 2012.

Hocking, D. J. *Invited Seminar*: A great leap backwards: amphibians in crisis. 2009 Department of Natural Resources and the Environment Seminar Series, UNH, Durham, NH.

Hocking, D. J. The role of salamanders in ecosystems. 2008 NRESS Student Seminar Series, University of New Hampshire.

Hocking, D. J., C. A., Conner, E. D. McDonald**, B. Scheffers, and R. D. Semlitsch. Initial Effects of Experimental Forest Management on a Terrestrial, Woodland Salamander in Missouri. 2008 Joint Meetings of Ichthyologists and Herpetologists, Montreal, Canada.

Hocking, D. J. and R. D. Semlitsch. Breeding Site Selection and Tadpole Performance of the Gray Treefrog (*Hyla versicolor*) in Response to a Forest Gradient. 2007 Ecological Society of America Annual Meeting, San Jose, CA.

Hocking, D. J.  Gray treefrog breeding site selection and offspring performance in response to forest management. 2007 Division of Biological Sciences Ecology Seminar Series, University of Missouri. 

Hocking, D. J.  The effects of forest management on larval treefrogs: implications for populations. 2006 Division of Biological Sciences Ecology Seminar Series, University of Missouri. 

Hocking, D. J. and R. D. Semlitsch.  The use of experimental pools for oviposition by gray treefrogs (*Hyla versicolor*) in four managed forest habitats. 2005 Midwest Fish and Wildlife Conference.  

## Poster Presentations

Hocking, D.J. and L.G. Smith. Hierarchical Bayesian models for climate reconstruction and uncertainty using tree rings. 2019. American Association of Geographers Annual Meeting. Washington, DC. [https://doi.org/10.6084/m9.figshare.8210513.v1](https://doi.org/10.6084/m9.figshare.8210513.v1)

Hocking, D.J., J. Thorson, K. O'Neil, and B.H. Letcher. A geostatistical state-space model of animal abundance for stream networks. 2018. American Association of Geographers Annual Meeting. New Orleans, LA.

Brooks, J.L.\*, and D.J. Hocking. The Effects of Acid Mine Drainage and Stream Restoration on Stream-breeding Salamanders. Frostburg State University. Graduate Research Symposium. 08 May 2018. 

Haydt, N.T.\*, and D.J. Hocking. Spatial Patterning of Turtle Populations Along the Chesapeake and Ohio Canal. Frostburg State University. Graduate Research Symposium. 08 May 2018. 

Braun, I.\*\*, E. Gaylord\*\*, N. Morris\*\*, F. Sherrard\*\*, and D.J. Hocking. Amphibian Presence and Abundance of Blue Lick Run. Frostburg State University. CLAS Undergraduate Research Symposium. 04 May 2018.

Devine, H.\*\*,  R. Phillip\*\*, S. Cain\*\*, M. Rogers\*\*, and D.J. Hocking. Amphibian and Reptile Survey of Dan’s Mountain WMA. Frostburg State University. CLAS Undergraduate Research Symposium. 04 May 2018.

Stum, M.\*\*, A. Waugh\*\*, D. Moss\*\*, M. McKenzie\*\*, J.L. Brooks\*, and D.J. Hocking. Amphibian and Reptile Survey of Warrior Mountain State Wildlife Management Area. Frostburg State University. CLAS Undergraduate Research Symposium. 04 May 2018.

Buckwalter, S.\*\*, K. Cagnasso\*\*, B. Moon\*\*, E. Schmidt\*\*, and D.J. Hocking. A Survey of Amphibian and Reptile Fauna at Mount Aetna. Frostburg State University. CLAS Undergraduate Research Symposium. 04 May 2018.

Hansen, J.\*\* and D.J. Hocking. Maryland’s Herpetofauna: Expanding the FSU Amphibian and Reptile Teaching Collection. Frostburg State University. CLAS Undergraduate Research Symposium. 04 May 2018.

Hocking, D. J., K. J. Babbitt, M. Yamasaki. Improved Estimation of Forestry Edge Effects Accounting for Detection Probability. 2013. ESA Annual Meeting. Minneapolis, MN. [http://dx.doi.org/10.6084/m9.figshare.776927](http://dx.doi.org/10.6084/m9.figshare.776927)

Sargent, P. J.\*\*, D. J. Hocking, K. J. Babbitt. Relating Hematological Patterns in Red-backed Salamanders to Stress in Different Habitats and Densities. 2013. Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J. and K. J. Babbitt. Comparisons of models for analyzing seasonal activity using longitudinal count data. World Congress of Herpetology Meeting. Vancouver, BC, Canada. 8-13 August 2012.

Marquis, A. J.\*\*, D. J. Hocking, K. J. Babbitt. Landscape and local-scale effects on stream salamanders in southeastern New Hampshire. 2012. Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J., and K. J. Babbitt. The contribution of woodland salamanders in ecosystem functions. 2010 Joint Meetings of Ichthyologists and Herpetologists, Providence, RI.

Willey, E.\*\*, D. J. Hocking, K. J. Babbitt. The effects of forest fragmentation on the abundance and body condition of the red backed salamander (*Plethodon cinereus*). 2010 Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J. Contributions of Salamanders to Ecosystem Functions and Services. 2009 Graduate Research Conference, UNH, Durham, NH.

Hocking, D. J., S. A. Callaghan, K. J. Babbitt, M. Yamasaki. The Effects of Natural and Anthropogenic Disturbance on Red-backed Salamanders in Northern Hardwood Forests. 2008 Joint Meetings of Ichthyologists and Herpetologists, Montreal, Canada.

Hocking, D. J., S. A. Callaghan, K. J. Babbitt, M. Yamasaki. The Effects of Natural and Anthropogenic Disturbance on Red-backed Salamanders in Northern Hardwood Forests. 2008 Northeast Partners for Amphibian and Reptile Meeting, Powdermill, PA.

Hocking, D. J., T. A. G. Rittenhouse, B. B. Rothermel, J. R. Johnson, C. A. Conner, E. B. Harper, and R. D. Semlitsch. Breeding and recruitment phenology of amphibians in Missouri oak-hickory forests. 2007 Joint Meeting of Ichthyologists and Herpetologists, St. Louis, MO.

Hocking, D. J. and R. D. Semlitsch. Effects of forest management on larval gray treefrogs (*Hyla versicolor*). 2007 Life Sciences Week, University of Missouri.

Hocking, D. J. and R. D. Semlitsch.  Effects of forest management on larval gray treefrogs. 2006 Midwest and Northeast meetings of Partners for Amphibian and Reptile Conservation. 

Hocking, D. J. and R. D. Semlitsch.  Oviposition site selection by gray treefrogs (*Hyla versicolor*) in four experimental forest habitats. 2006 University of Missouri Life Sciences Week. 

Barlows, A.\*\*, D. J. Hocking, and R. D. Semlitsch.  Effects of shade and predation on survival and growth of larval gray treefrogs (*Hyla versicolor*) in Missouri.  2006 University of Missouri-Columbia Undergraduate Research and Creative Achievements Forum.  

Mahan, R. D.\*\*, B. B. Rothermel, D. J. Hocking, J. W. Gibbons, and R. D. Semlitsch. Effects of forest management practices on treefrog oviposition site choice. 2005 Summer Undergraduate Research and Creative Achievements Forum, University of Missouri, Columbia, MO.

Mahan, R. D.\*\*, B. B. Rothermel, D. J. Hocking, J. W. Gibbons, and R. D. Semlitsch. Effects of forest management practices on treefrog oviposition site choice. 2005 Research Experiences for Undergraduates Program, University of Georgia’s Savannah River Ecology Laboratory.

Wason, C., M. Giguere, M. Driscoll, L. Seydewitz, D. J. Hocking, E. Falton, J. Baker, M. Novak, S. Bradt, J. Campbell, R. Blakemore, and A. Baker.  Project Lake Watch: On Golden Pond for lake truthing Landsat and MODIS. 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography.

Seydewitz, L., M. Driscoll, C. Wason, M. Giguere, D. J. Hocking, E. Falton, J. Baker, M. Novak, S. Bradt, A. Baker, R. Blakemore, and J. Campbell.  Project Lake Watch: Monitoring New Hampshire lakes from canoes and satellites. 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography. 

Falton, E., D. J. Hocking, C. Wason, J. Baker, M. Giguere, L. Seydewitz, M. Driscoll, M. Novak, S. Bradt, J. Campbell, R. Blakemore, and A. Baker.  Project Lake Watch: Looking at lakes with microscopes and satellites. Presented at the 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography. 
\newpage

# Qualifications

## Degree Qualificiations

I have a Ph.D. in Natural Resources and Environmental Studies, a Masters degree in Biological Sciences, and an undergraduate B.S. degree in Environmental Conservation, science option with a minor in Chemical Engineering. All three of these degrees are "directly related to the position". They focused on the collection, management, analysis, and interpretation of natural resource and ecological data using mathematical, statistical, and computational techniques and communicating the results to diverse audiences as needed in data science.

## Education and Experience

I believe that my major degrees provide adequate evidence of my qualifications for the basic degree requirements. However, the titles of courses and the degrees are a bit general and so I included below a list of courses and experiences that would also qualify in this category and benefit me in this position.

## Courses

- MATH 941 Bayesian Statistics (3 cr) - Statistical methods for quantifying uncertainty for data science with automation in the R programming language

- NR 997 Special Topics in US Environmental Policy in Application (3 cr) - US environmental policy application with fisheries focus taught by Dr. Andy Rosenburg, former northeast regional administrator of the National Marine Fisheries Service at the National Oceanic and Atmospheric Administration.

- BioSc 8700 Ecological Genetics (4 cr) - Understanding ecological genetic concepts but also how to process large amounts of automated genetic data using bash, regular expressions, Python, and other tools in a unix-base system

- BioSc 8600 Design of Ecological Experiments (3 cr) - How to design ecological experiments and manage the full research data cycle

- BioSc 9090 Research in the Biological Sciences (3 cr) - Designed a data collection system using PenDragon software on Palm Pilots to interface with a custom designed MS Access database to reduce data entry time and greatly reduce transcription data errors along with automating data checks to prevent incompatible data entry errors
- Stat 7530 Analysis of Variance (3 cr) - Using the SAS programming system to analyze data from different comparative research study designs

- NatR 7325 Introduction to Geographic Information Systems (3 cr) - Using GIS data systems to organize, analyze, and map spatial data for Natural Resources

- Stat 7510 Regression and Correlation Analysis (3 cr) - Regression analysis and automation in the R programming language

- BioSc 8187 Seminar in Areas of Specialization 2006 (1 cr) - Learning MatLab programming for analysis and visualization of animal movement data

- BioSc 8090 Research in Biological Sciences 2006 (8 cr) - Supervised research focused on quantitative methods for movement and population assessment, using both the SAS and R programming languages

- NR 765 Community Ecology (4 cr) - Understanding and quantifying community ecology data

- BIOL 603 Seminar for Project Lake Watch (3 cr) - Integrating and analyzing aquatic samples and satellite imagery data using MatLab and preparing presentations for scientific meetings

- NR 713 Quantitative Ecology (4 cr) - Managing and analyzing ecological data for natural resources and ecological systems

- NR 602 Natural Resources and Environmental Policy (4 cr) - Overview of natural resource and environmental laws, policies, and regulations used in the management of marine, freshwater, and terrestrial systems

- SOC 502 Statistics (4 cr) - Introduction to Statistics

- EC 535 Contemporary Conservation Issues (4 cr)

- EREC 411 Environmental and Resource Economic Perspectives (4 cr) - Introduction to economics for natural resources

- CS 410 Introduction to Scientific Programming in C (4 cr) - Introduction to scientific programming in the C language for engineers

- MATH 527 Differential Equations and Linear Algebra (4 cr) - Mathematical basis for most statistical and data science applications

- MATH 526 Calculus II (4 cr)

- MATH 525H Honors Calculus I (4 cr)

## Basic Experience

- Taught university course on Quantitative methods at Frostburg State University

- Published scientific papers on new quantitative methods for spatiotemporal analysis of fish data

- Managed a research laboratory as an assistant professor including data collection, management, analysis, and visualization

- Developed databases using various software platforms and automated analyses and web interfaces from these databases as a graduate student, professor, and now in my current role at NOAA

## Specialized Experience

- Worked for two years in Federal Service at USGS at a GS-12 grade level that included Conducting research into new technology or methods, determining system requirements, and coordinating efforts with fisheries scientists and managers, as well as resolving fisheries data science challenges with new and innovative software approaches and advise suggestions for improvement and enhancements on a continual basis throughout the software development life cycle.

- I have worked for 2.5 years at the NOAA Greater Atlantic Regional Fisheries Office (GARFO) at a ZP-03 grade level and my work as included both criteria of 1) Conducting research into new technology or methods, determining system requirements, and coordinating efforts with fisheries scientists and managers, and 2) Resolving fisheries data science challenges with new and innovative software approaches and advise suggestions for improvement and enhancements on a continual basis throughout the software development life cycle.
