---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: latex_cv.tex
geometry: margin=1in

title: "CV"
author: Daniel J. Hocking

jobtitle: "Assistant Professor, Frostburg State University"
address: "Department of Biology · 101 Braddock Road · Frostburg, MD 21532"
fontawesome: yes
email: djhocking@frostburg.edu
github: djhocking
phone: "301-687-4343"
web: hockinglab.weebly.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Professional Experience

2016 - present \hspace{1mm} Assistant Professor, Dept. of Biology, Frostburg State University

2014 – 2016 \hspace{5mm} USGS Mendenhall Postdoctoral Fellow, Conte Anadromous Fish Research Lab

2014 – 2016 \hspace{5mm} Postdoctoral Fellow, DOI Northeast Climate Science Center

2012 – 2013 \hspace{5mm} Postdoctoral Research Associate, University of New Hampshire

# Education

2012 \hspace{4mm} PhD Natural Resources & Environmental Science, University of New Hampshire  

2007 \hspace{4mm} MA Biological Sciences, University of Missouri

2003 \hspace{4mm} BS Environmental Science, University of New Hampshire

# Publications

[Google Scholar](https://scholar.google.com/citations?user=qIFCelIAAAAJ)
(citations = 679, *h*-index = 13, *i*10-index = 14)  
\*\*undergraduate, \*graduate student, <sup>+</sup>postdoc

**Hocking, D.J.**, J.A. Crawford, W.E. Peterman, and J.R. Milanovich. *in prep*. Setting the baseline: Estimates of current elevational distributions for understanding future climate effects.

Sterrett, S.C., R.A. Katz, A.B. Brand, W.R. Fields, A.E. Dietrich, **D.J. Hocking**, T.M. Foreman, A.N.M. Wiewel, E.H. Campbell Grant. *In Review*. Proactive management of amphibians: Challenges and opportunities.

Pregler, K.C., R.D. Hanks, E. Childress, N.P. Hitt, **D.J. Hocking**, B.H. Letcher, T. Wagner, and Y. Kanno. *In Review*. State-space analysis of power to detect regional brook trout population trends over time.

**Hocking, D.J.**, K. O'Neil, and B.H. Letcher. *In Review*. A hierarchical model of daily stream temperature for regional predictions. [[Code](https://github.com/Conte-Ecology/conteStreamTemperature_northeast), [Data](http://db.ecosheds.org/), [Preprint](https://github.com/Conte-Ecology/conteStreamTemperature_northeast/blob/master/manuscripts/northeast_temperature_ms.pdf)]

**Hocking, D.J.**, J. Thorson, K. O'Neil, and B.H. Letcher. *In Press*. A geostatistical state-space model of animal abundance for stream networks. Ecological Applications.

Earl, J.E., E.B. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, M. Glennie, and R.D. Semlitsch. 2017. Relative importance of timber harvest and habitat for reptiles in experimental forestry plots. 402: 21-28. [https://doi.org/10.1016/j.foreco.2017.07.014](https://doi.org/10.1016/j.foreco.2017.07.014)

Stephens, R.B.\*, **D.J. Hocking**, M. Yamasaki, and R.J. Rowe. 2017. Synchrony in small mammal community dynamics across a forested landscape. Ecography. 40: 1198–1209. [http://dx.doi.org/10.1111/ecog.02233](http://dx.doi.org/10.1111/ecog.02233). [Data](http://datadryad.org/resource/doi:10.5061/dryad.76jr5)

Buckman, K., V. Taylor, H. Broadley, **D.J. Hocking**, P. Balcom, R. Mason, K. Nislow, and C. Chen. 2017. Landscape influences on methylmercury bioaccumulation in an urban estuary: Delaware River, USA. Estuaries and Coasts. 40(5):1358–1370. [https://link.springer.com/article/10.1007](https://link.springer.com/article/10.1007)

Earl, J.E., E. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, and R.D. Semlitsch. 2016. Effects of timber harvest on small mammal captures in experimental forestry plots. Animal Biology. 66:347 – 362 [http://dx.doi.org/10.1163/15707563-00002511](http://dx.doi.org/10.1163/15707563-00002511)

Letcher, B.H., **D.J. Hocking**, K. O'Neil, A.R. Whiteley, K.H. Nislow, and M.J. O'Donnell. 2016. A hierarchical model of daily stream temperature using air-water temperature synchronization, autocorrelation, and time lags. PeerJ. 4:e1727 [https://doi.org/10.7717/peerj.1727](https://doi.org/10.7717/peerj.1727)

Peterman, W.E., J.A. Crawford, and **D.J. Hocking**. 2016. Effects of elevation on plethodontid salamander body size. Copeia. 104(1):202-208. [http://dx.doi.org/10.1643/OT-14-188](http://dx.doi.org/10.1643/OT-14-188)

Milanovich, J.R., **D.J. Hocking**, W.E. Peterman, and J.A. Crawford. 2016. Effective use of trails for assessing terrestrial salamander abundance and detection:  A case study at Great Smoky Mountains National Park. Natural Areas Journal. 35(4):590-598. [http://dx.doi.org/10.3375/043.035.0412](http://dx.doi.org/10.3375/043.035.0412)

Anderson, T.L., **D.J. Hocking**, C.A. Conner, J.E. Earl, E.B. Harper, M.S. Osbourn, W.E. Peterman, T.A.G. Rittenhouse, and R.D. Semlitsch. 2015. Abundance and phenology patterns of two pond-breeding salamanders determine species interactions in natural populations. Oecologia. 177(3):761-73. [http://dx.doi.org/10.1007/s00442-014-3151-z](http://dx.doi.org/10.1007/s00442-014-3151-z)

Drake, D.L, B.H. Ousterhout, C.D. Shulse, **D.J. Hocking**, W.E. Peterman, T.A. Anderson, K.L. Lohraff, C.A. Conner, E.H. Harper, J.R. Johnson, T.A.G. Rittenhouse, B.B. Rothermel, L.S. Eggert, and R.D. Semlitsch. 2015. Pond-breeding amphibian community composition in Missouri. American Midland Naturalist. 174:180-187.

**Hocking, D.J.** and K.J. Babbitt. 2014. Amphibian Contributions to Ecosystem Services. Herpetological Conservation and Biology. 9(1):1-17. [**OA**]

**Hocking, D.J.** and K.J. Babbitt. 2014. The role of red-backed salamanders on ecosystem functions. PLoS ONE 9(1):e86854. [http://dx.doi.org/10.1371/journal.pone.0086854](http://dx.doi.org/10.1371/journal.pone.0086854) [**OA**]

**Hocking, D.J.** 2013. Comparing the influence of ecology journals using citation metrics: making sense of a multitude of metrics. Ideas in Ecology & Evolution. 6(1): 55–65. [http://dx.doi.org/10.4033/iee.v6i1.4949](http://dx.doi.org/10.4033/iee.v6i1.4949) [**OA**]

**Hocking, D.J.**, S.A. Callaghan, K.J. Babbitt, and M. Yamasaki. 2013. Comparison of silvicultural and natural disturbance effects on terrestrial salamanders in northern hardwood forests. Biological Conservation. 167:194-202. [http://dx.doi.org/10.1016/j.biocon.2013.08.006](http://dx.doi.org/10.1016/j.biocon.2013.08.006)

**Hocking, D.J.**, G.M. Connette, C.A. Conner, B.R. Scheffers, S.E. Pittman, W.E. Peterman, R.D. Semlitsch. 2013. Effects of experimental forest management on a terrestrial, woodland salamander in Missouri. Forest Ecology and Management. 287:32-39

Osbourn, M.S., **D.J. Hocking**, C.A. Conner, W.E. Peterman, and R.D. Semlitsch. 2011. Use of fluorescent visible implant Alphanumeric tags to individually mark juvenile ambystomatid salamanders. Herpetological Review 42(1):43-46.

**Hocking, D.J.** 2010. *Hyla squirella* (squirrel treefrog) reproduction. Herpetological Review 41(1):64.

Semlitsch, R.D., S.M. Blomquist, A.J.K. Calhoun, J.W. Gibbons, J.P. Gibbs, G.J. Graeter, E.B. Harper, **D.J. Hocking**, M.L. Hunter, D.A. Patrick, T.A.G. Rittenhouse, B.B. Rothermel, and B.D. Todd. 2009. Effects of timber management on amphibian populations: understanding mechanisms from forest experiments. Bioscience 59(10):853-862. (Cover Photograph)

Scheffers, B., E.D. McDonald, **D.J. Hocking**, C.A. Conner, and R.D. Semlitsch. 2009. A comparison of two artificial cover objects for sampling amphibians and reptiles. Herpetological Review 40(4):419-421.

Babbitt K.J., M.J. Baber, D.L. Childers, and **D.J. Hocking**. 2009. The influence of agricultural upland habitat type on larval anuran assemblages in seasonally-inundated wetlands. Wetlands 29(1):294-301.

**Hocking, D.J.** and R.D. Semlitsch. 2008. Effects of clearcut logging on gray treefrog (Hyla versicolor) tadpole performance. Journal of Herpetology 42:689-698.

**Hocking, D.J.**, T.A.G. Rittenhouse, B.B. Rothermel, J.R. Johnson, C.A. Conner, E.B. Harper, and R.D. Semlitsch. 2008. Breeding and recruitment phenology of amphibians in Missouri oak-hickory forests. American Midland Naturalist 160:41-60.

Semlitsch, R.D., C.A. Conner, **D.J. Hocking**, T.A.G. Rittenhouse, and E.B. Harper. 2008. Effects of timber harvesting on pond-breeding amphibian persistence: testing the evacuation hypothesis. Ecological Applications 18(2):283-289.

**Hocking, D.J.** and R.D. Semlitsch. 2007. Effects of timber harvest on breeding site selection by gray treefrogs (Hyla versicolor). Biological Conservation 138:506-513.

# Grants Awarded (Total: $426,599)

National Park Service. Natural Resource Stewardship and Science FY19 Servicewide Comprehensive Call. Effects of wildfire on salamander populations in Great Smoky Mountains National Park. D.J. Hocking, J.A. Crawford, W.E. Peterman, and J.R. Milanovich. 2019 Pending Congressional Authorization. $76,464.

Frostburg Foundation Opportunity Grant. Effects of acid mine drainage and stream restoration on Plethodontid salamanders. D.J. Hocking and J. Brooks. 2018. $1,329. 

Frostburg State University. Faculty Development Graduate Research Grant. Spatial patterns, home ranges, and associated parasites in the Chesapeake and Ohio Canal National Historic Park. D.J. Hocking and Natalie Haydt. 2018. $1,500.

Appalachian Highlands Science Learning Center Research Grants. Effects of Wildlife on Salamander Populations in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, and J.R. Milanovich. 2018. $2,000

Great Smoky Mountains Conservation Association. Carlos C. Campbell and James T. Tanner Memorial Fund. Short-term Effects of Wildlife on Salamander Populations in Great Moky Mountains National Park. D.J. Hocking, J.A. Crawford, W.E. Peterman, J.R. Milanovich. 2017. $5,000

Appalachian Highlands Science Learning Center Research Grants. Short-term Effects of Wildlife on Salamander Populations in Great Moky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, J.R. Milanovich. 2017. $1,124

Frostburg State University. Faculty Development Undergraduate Research Grant. D.J. Hocking. 2017. $3,750.

Frostburg State University CLAS Strategic Plan Fund. Salamander population and adaptation research collaborative network. D.J. Hocking. 2017. $500

USGS Mendenhall Research Fellowship. Hierarchical modeling of climate change effects: Land-use impacts on brook trout population persistence. 2014-2016. $250,000

National Geographic Society. Waitt Grant. Climate change effects on elevational distributions of salamanders in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, J. Milanovich, W.E. Peterman. 2012. $14,932
 
NH Agricultural Experiment Station. McIntire-Stennis. The role of red-backed salamanders (*Plethodon cinereus*) in forest-floor ecosystem functions. K.J. Babbitt, D.J. Hocking. 2011. $42,000

University of New Hampshire. Dissertation Year Fellowship. The contributions of woodland salamanders to ecosystem functions. 2011. $16,000

University of Missouri. Trans-World Airlines Scholarship. The effects of predators on gray treefrog (*Hyla versicolor*) growth, survival, and development. 2006. $7,000

# Teaching

## Courses

* General Ecology (BIOL 340), Frostburg State University. 2016 - present. Spring, Fall.

* Herpetology (BIOL 422/522), Frostburg State University. 2017 - present. Spring.

* Quantitative Analysis of Vertebrate Populations (BIOL 414/514). 2017 - present. Fall.

* General Zoology Laboratory (BIOL 160). 2016 - present. Variable.

* Vertebrate Biology (NR 655), University of New Hampshire. 2009.

* Introduction to Conservation Biology (BIO 105), Moberly Area Community College, Columbia, MO. 2007.

## Teaching Assistant

* 2007, 2009  Wildlife Techniques (NR 646), University of New Hampshire

* 2008        Conservation Biology (NR 650), University of New Hampshire

## Tutor

* 2010        Introductory Biology (Bio 412), University of New Hampshire

* 2010        Freshwater Resources (NR 504), University of New Hampshire

* 2008-2010   Sociology Statistics (Soc 502), University of New Hampshire

* 2009        Contemporary Conservation Issues (NR 435), University of New Hampshire

## Certifications

* Cognate in College Teaching, Center for Excellence in Teaching & Learning, University of New Hampshire

* Software Carpentry Instructor, Teaching Lab Skills for Scientific Computing [http://software-carpentry.org/](http://software-carpentry.org/) 

# Research Mentoring

## Graduate Students

* Natalie Haydt, Spatial capture-recapture and disease of turtles along a depth gradient in the C&O Canal. 2017 - present

* Jacey Brooks, The effects of Acid Mine Drainage and remediation on stream salamander populations. 2017 - present

* Bethany Liberto, Abundance and distribution of rare dragonflies in high elevation bogs. *Co-advised with Dr. Jered Studinski*. 2017 - present

## Graduate Student Committees

Ryan Stephens (PhD, University of New Hampshire, 2018); Sabrina Edwards (MS, Frostburg State University); Emily Harlan (MS, Frostburg State University); Erica Duda (MS, Frostburg State University); Elizabeth Greene (MS, Frostburg State University)

## Undergraduate Researchers

I have mentored 13 undergraduate students (6 women, 7 men) on independent research projects, including multiple first generation college students and one U.S. Army Veteran. 

# Professional and Community Service

## University Service

* Faculty Senate Ad-Hoc Committee on Evaluations II 

## Department Service

* Wildlife and Fisheries and Interpretive Biology and Natural History Curriculum Committee. 2017-present.

* The Wildlife Society, Frostburg State University Chapter. Faculty Advisor. 2017-present.

* Campus Tree Committee, Frostburg State University. 2016-present.

* R Programming and Statistical Users Group, Faculty Advisor, Frostburg State University. 2017-present. [https://frostburgrusers.wordpress.com/](https://frostburgrusers.wordpress.com/)

* Hiring committee. Full-Time, Non-Tenure Track Faculty to teach Introductory Biology, Zoology, and Anatomy and Physiology. 2018.

* Department Evaluation Committee, Biology Department, Frostburg State University. 2016-2017.

## General

* Organizing Committee. Northeastern Stream Temperature Monitoring and Analysis Meeting. US Fish and Wildlife Service. Region 5 Regional Office. Hadley, MA. 21-22 February 2017.

* Cofounded the New Hampshire R Users Group [http://www.nhusers.wordpress.com](http://www.nhusers.wordpress.com), including organizing weekly meetings and securing corporate sponsorship. 2013 – 2014.

* Organizer. NRESS Seminar. University of New Hampshire. Helped organize the spring seminar series for the Natural Resource and Earth System Science program. 2008.

* Vice President. Biology Graduate Student Association. University of Missouri. 2005-2006.

* Webmaster. Land-use Effects on Amphibian Populations (LEAP) Collaboration (www.leap.missouri.edu). 2004-2005.

* Webmaster. Missouri Chapter of the Society for Conservation Biology. 2005-2006.

* Co-Chair. Outreach Committee for the Missouri Chapter of the Society for Conservation Biology. 2005-2006.

## Outreach

* Taxonomic Expert. Gulf of Maine Research Institute, Vital Signs citizen science program. 2014 – present.

* Guest Speaker. Great Smoky Mountain Institute at Tremont, GSMNP, NC. July 2012. Talked to a science camp group about salamander biodiversity in Great Smoky Mountains National Park.

* Guest Speaker. Traip Academy, Kittery, ME. May 2011. Discussed college programs in math and science and career paths in ecology and conservation with high school seniors.

* Guest Speaker. Dover High School, Dover, NH. February 2008. Discussed the writing process with sophomore English classes.

* Guest Speaker. Hickman Highschool Biology Club. October 2006. Amphibians, reptiles, and college planning for aspiring biologists.

* BioBlitz Organizer and Team Leader. Columbia, MO. 2005-2006, [http://BioBlitz.missouri.edu](http://BioBlitz.missouri.edu).

## Manuscript Reviewing

AMBIO, Bioscience, Conservation Biology, Copeia, Ecological Applications, Ecology and Evolution, Ecosphere, Forest Ecology and Management, Freshwater Biology, Global Change Biology, Herpetological Conservation and Biology, Herpetological Review, Journal of Herpetology, Journal of Wildlife Management, Northeastern Naturalist, Oikos, PeerJ, PLoS ONE, Urban Ecosystems, Wetlands

# Presentations

\*\*undergraduate, \*graduate student, <sup>+</sup>postdoc

## Oral Presentations

Hocking, D.J. *Invited Seminar*: Models and Visualization of Regional Stream Temperature and Trout Populations. University of Maryland Center for Environmental Science. Appalachian Laboratory. 11 May 2017.

Hocking, D.J. Climate effects on brook trout populations. NECSC Colloquium Webinar. DOI Northeast Climate Science Center, University of Massachusetts-Amherst. [https://necsc.umass.edu/webinars/early-career-showcase](https://necsc.umass.edu/webinars/early-career-showcase). 23 March 2016.

Hocking, D. J., B. Letcher, K. Nislow, Y. Kanno, M. Ratnaswamy, and J. Wofford. Using single-pass surveys to assess spatial and temporal patterns in Brook Trout abundance: Correcting for imperfect detection. American Fisheries Society Annual Meeting, Quebec City, Canada. August 17-21, 2014.

Hocking, D. J. *Invited Seminar*: The effects of land-use and climate change on amphibian populations. Environmental Science Seminar Series. University of New Hampshire, Durham, NH. October 11, 2013.

Hocking, D. J. and K. J. Babbitt. Comparisons of models for analyzing seasonal activity using longitudinal count data. Ecological Society of America Annual Meeting, Portland, OR. August 4-10, 2012.

Hocking, D. J. *Invited Seminar*: A great leap backwards: amphibians in crisis. 2009 Department of Natural Resources and the Environment Seminar Series, UNH, Durham, NH.

Hocking, D. J. The role of salamanders in ecosystems. 2008 NRESS Student Seminar Series, University of New Hampshire.

Hocking, D. J., C. A., Conner, E. D. McDonald**, B. Scheffers, and R. D. Semlitsch. Initial Effects of Experimental Forest Management on a Terrestrial, Woodland Salamander in Missouri. 2008 Joint Meetings of Ichthyologists and Herpetologists, Montreal, Canada.

Hocking, D. J. and R. D. Semlitsch. Breeding Site Selection and Tadpole Performance of the Gray Treefrog (Hyla versicolor) in Response to a Forest Gradient. 2007 Ecological Society of America Annual Meeting, San Jose, CA.

Hocking, D. J.  Gray treefrog breeding site selection and offspring performance in response to forest management. 2007 Division of Biological Sciences Ecology Seminar Series, University of Missouri. 

Hocking, D. J.  The effects of forest management on larval treefrogs: implications for populations. 2006 Division of Biological Sciences Ecology Seminar Series, University of Missouri. 

Hocking, D. J. and R. D. Semlitsch.  The use of experimental pools for oviposition by gray treefrogs (Hyla versicolor) in four managed forest habitats. 2005 Midwest Fish and Wildlife Conference.  

## Poster Presentations

Hocking, D.J., J. Thorson, K. O'Neil, and B.H. Letcher. A geostatistical state-space model of animal abundance for stream networks. 2018. American Association of Geographers Annual Meeting. New Orleans, LA.

Brooks, J.L.\*, and D.J. Hocking. The Effects of Acid Mine Drainage and Stream Restoration on Stream-breeding Salamanders. Frostburg State University. Graduate Research Symposium. May 8, 2018. 

Haydt, N.T.\*, and D.J. Hocking. Spatial Patterning of Turtle Populations Along the Chesapeake and Ohio Canal. Frostburg State University. Graduate Research Symposium. May 8, 2018. 

Braun, I.\*\*, E. Gaylord\*\*, N. Morris\*\*, F. Sherrard\*\*, and D.J. Hocking. Amphibian Presence and Abundance of Blue Lick Run. Frostburg State University. CLAS Undergraduate Research Symposium. May 4, 2018

Devine, H.\*\*,  R. Phillip\*\*, S. Cain\*\*, M. Rogers\*\*, and D.J. Hocking. Amphibian and Reptile Survey of Dan’s Mountain WMA. Frostburg State University. CLAS Undergraduate Research Symposium. May 4, 2018

Stum, M.\*\*, A. Waugh\*\*, D. Moss\*\*, M. McKenzie\*\*, J.L. Brooks\*, and D.J. Hocking. Amphibian and Reptile Survey of Warrior Mountain State Wildlife Management Area. Frostburg State University. CLAS Undergraduate Research Symposium. May 4, 2018

Buckwalter, S.\*\*, K. Cagnasso\*\*, B. Moon\*\*, E. Schmidt\*\*, and D.J. Hocking. A Survey of Amphibian and Reptile Fauna at Mount Aetna. Frostburg State University. CLAS Undergraduate Research Symposium. May 4, 2018

Hansen, J.\*\* and D.J. Hocking. Maryland’s Herpetofauna: Expanding the FSU Amphibian and Reptile Teaching Collection. Frostburg State University. CLAS Undergraduate Research Symposium. May 4, 2018

Hocking, D. J., K. J. Babbitt, M. Yamasaki. Improved Estimation of Forestry Edge Effects Accounting for Detection Probability. 2013. ESA Annual Meeting. Minneapolis, MN. [http://dx.doi.org/10.6084/m9.figshare.776927](http://dx.doi.org/10.6084/m9.figshare.776927)

Sargent, P. J.\*\*, D. J. Hocking, K. J. Babbitt. Relating Hematological Patterns in Red-backed Salamanders to Stress in Different Habitats and Densities. 2013. Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J. and K. J. Babbitt. Comparisons of models for analyzing seasonal activity using longitudinal count data. World Congress of Herpetology Meeting. Vancouver, BC, Canada. August 8-13, 2012.

Marquis, A. J.\*\*, D. J. Hocking, K. J. Babbitt. Landscape and local-scale effects on stream salamanders in southeastern New Hampshire. 2012. Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J., and K. J. Babbitt. The contribution of woodland salamanders in ecosystem functions. 2010 Joint Meetings of Ichthyologists and Herpetologists, Providence, RI.

Willey, E.\*\*, D. J. Hocking, K. J. Babbitt. The effects of forest fragmentation on the abundance and body condition of the red backed salamander (Plethodon cinereus). 2010 Undergraduate Research Conference, UNH, Durham, NH.

Hocking, D. J. Contributions of Salamanders to Ecosystem Functions and Services. 2009 Graduate Research Conference, UNH, Durham, NH.

Hocking, D. J., S. A. Callaghan, K. J. Babbitt, M. Yamasaki. The Effects of Natural and Anthropogenic Disturbance on Red-backed Salamanders in Northern Hardwood Forests. 2008 Joint Meetings of Ichthyologists and Herpetologists, Montreal, Canada.

Hocking, D. J., S. A. Callaghan, K. J. Babbitt, M. Yamasaki. The Effects of Natural and Anthropogenic Disturbance on Red-backed Salamanders in Northern Hardwood Forests. 2008 Northeast Partners for Amphibian and Reptile Meeting, Powdermill, PA.

Hocking, D. J., T. A. G. Rittenhouse, B. B. Rothermel, J. R. Johnson, C. A. Conner, E. B. Harper, and R. D. Semlitsch. Breeding and recruitment phenology of amphibians in Missouri oak-hickory forests. 2007 Joint Meeting of Ichthyologists and Herpetologists, St. Louis, MO.

Hocking, D. J. and R. D. Semlitsch. Effects of forest management on larval gray treefrogs (Hyla versicolor). 2007 Life Sciences Week, University of Missouri.

Hocking, D. J. and R. D. Semlitsch.  Effects of forest management on larval gray treefrogs. 2006 Midwest and Northeast meetings of Partners for Amphibian and Reptile Conservation. 

Hocking, D. J. and R. D. Semlitsch.  Oviposition site selection by gray treefrogs (Hyla versicolor) in four experimental forest habitats. 2006 University of Missouri Life Sciences Week. 

Barlows, A.\*\*, D. J. Hocking, and R. D. Semlitsch.  Effects of shade and predation on survival and growth of larval gray treefrogs (Hyla versicolor) in Missouri.  2006 University of Missouri-Columbia Undergraduate Research and Creative Achievements Forum.  

Mahan, R. D.\*\*, B. B. Rothermel, D. J. Hocking, J. W. Gibbons, and R. D. Semlitsch. Effects of forest management practices on treefrog oviposition site choice. 2005 Summer Undergraduate Research and Creative Achievements Forum, University of Missouri, Columbia, MO.

Mahan, R. D.\*\*, B. B. Rothermel, D. J. Hocking, J. W. Gibbons, and R. D. Semlitsch. Effects of forest management practices on treefrog oviposition site choice. 2005 Research Experiences for Undergraduates Program, University of Georgia’s Savannah River Ecology Laboratory.

Wason, C., M. Giguere, M. Driscoll, L. Seydewitz, D. J. Hocking, E. Falton, J. Baker, M. Novak, S. Bradt, J. Campbell, R. Blakemore, and A. Baker.  Project Lake Watch: On Golden Pond for lake truthing Landsat and MODIS. 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography.

Seydewitz, L., M. Driscoll, C. Wason, M. Giguere, D. J. Hocking, E. Falton, J. Baker, M. Novak, S. Bradt, A. Baker, R. Blakemore, and J. Campbell.  Project Lake Watch: Monitoring New Hampshire lakes from canoes and satellites. 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography. 

Falton, E., D. J. Hocking, C. Wason, J. Baker, M. Giguere, L. Seydewitz, M. Driscoll, M. Novak, S. Bradt, J. Campbell, R. Blakemore, and A. Baker.  Project Lake Watch: Looking at lakes with microscopes and satellites. Presented at the 2003 Annual Aquatic Sciences Meeting of the American Society for Limnology and Oceanography. 