---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: latex_cv.tex
geometry: margin=1in

title: "CV"
author: Daniel J. Hocking

jobtitle: "Assistant Professor, Frostburg State University"
address: "Department of Biology · 101 Braddock Road · Frostburg, MD 21532"
fontawesome: yes
email: djhocking@frostburg.edu
github: djhocking
phone: "301-687-4343"
web: hockinglab.weebly.com

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Professional Experience

2016 - present \hspace{1mm} Assistant Professor, Dept. of Biology, Frostburg State University

2014 – 2016 \hspace{5mm} USGS Mendenhall Postdoctoral Fellow, Conte Anadromous Fish Research Lab

2014 – 2016 \hspace{5mm} Postdoctoral Fellow, DOI Northeast Climate Science Center

2012 – 2013 \hspace{5mm} Postdoctoral Research Associate, University of New Hampshire

# Education

2012 \hspace{4mm} PhD Natural Resources & Environmental Science, University of New Hampshire  

2007 \hspace{4mm} MA Biological Sciences, University of Missouri

2003 \hspace{4mm} BS Environmental Science, University of New Hampshire

# Publications

[Google Scholar](https://scholar.google.com/citations?user=qIFCelIAAAAJ)
(citations = 738, *h*-index = 13, *i*10-index = 16)  
\*\*undergraduate, \*graduate student, <sup>+</sup>postdoc

**Hocking, D.J.**, K. O'Neil, and B.H. Letcher. *In Revision*. A hierarchical model of daily stream temperature for regional predictions. [[Code](https://github.com/Conte-Ecology/conteStreamTemperature_northeast), [Data](http://db.ecosheds.org/), [Preprint](https://github.com/Conte-Ecology/conteStreamTemperature_northeast/blob/master/manuscripts/northeast_temperature_ms.pdf)]

Sterrett, S.C., R.A. Katz, A.B. Brand, W.R. Fields, A.E. Dietrich, **D.J. Hocking**, T.M. Foreman, A.N.M. Wiewel, E.H. Campbell Grant. *In Press*. Proactive management of amphibians: Challenges and opportunities. Biological Conservation.

Pregler, K.C., R.D. Hanks, E. Childress, N.P. Hitt, **D.J. Hocking**, B.H. Letcher, T. Wagner, and Y. Kanno. *In Press*. State-space analysis of power to detect regional brook trout population trends over time. Canadian Journal of Fisheries and Aquatic Sciences.

**Hocking, D.J.**, J. Thorson, K. O'Neil, and B.H. Letcher. 2018. A geostatistical state-space model of animal abundance for stream networks. Ecological Applications. 28: 1782-1796. [https://doi.org/10.1002/eap.1767](https://doi.org/10.1002/eap.1767)

Earl, J.E., E.B. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, M. Glennie, and R.D. Semlitsch. 2017. Relative importance of timber harvest and habitat for reptiles in experimental forestry plots. 402: 21-28. [https://doi.org/10.1016/j.foreco.2017.07.014](https://doi.org/10.1016/j.foreco.2017.07.014)

Stephens, R.B.\*, **D.J. Hocking**, M. Yamasaki, and R.J. Rowe. 2017. Synchrony in small mammal community dynamics across a forested landscape. Ecography. 40: 1198–1209. [http://dx.doi.org/10.1111/ecog.02233](http://dx.doi.org/10.1111/ecog.02233). [[Data](http://datadryad.org/resource/doi:10.5061/dryad.76jr5)]

Buckman, K., V. Taylor, H. Broadley, **D.J. Hocking**, P. Balcom, R. Mason, K. Nislow, and C. Chen. 2017. Landscape influences on methylmercury bioaccumulation in an urban estuary: Delaware River, USA. Estuaries and Coasts. 40(5):1358–1370. [https://link.springer.com/article/10.1007](https://link.springer.com/article/10.1007)

Earl, J.E., E. Harper, **D.J. Hocking**, M.S. Osbourn, T.A.G. Rittenhouse, and R.D. Semlitsch. 2016. Effects of timber harvest on small mammal captures in experimental forestry plots. Animal Biology. 66:347 – 362 [http://dx.doi.org/10.1163/15707563-00002511](http://dx.doi.org/10.1163/15707563-00002511)

Letcher, B.H., **D.J. Hocking**, K. O'Neil, A.R. Whiteley, K.H. Nislow, and M.J. O'Donnell. 2016. A hierarchical model of daily stream temperature using air-water temperature synchronization, autocorrelation, and time lags. PeerJ. 4:e1727 [https://doi.org/10.7717/peerj.1727](https://doi.org/10.7717/peerj.1727)

Peterman, W.E., J.A. Crawford, and **D.J. Hocking**. 2016. Effects of elevation on plethodontid salamander body size. Copeia. 104(1):202-208. [http://dx.doi.org/10.1643/OT-14-188](http://dx.doi.org/10.1643/OT-14-188)

Milanovich, J.R., **D.J. Hocking**, W.E. Peterman, and J.A. Crawford. 2016. Effective use of trails for assessing terrestrial salamander abundance and detection:  A case study at Great Smoky Mountains National Park. Natural Areas Journal. 35(4):590-598. [http://dx.doi.org/10.3375/043.035.0412](http://dx.doi.org/10.3375/043.035.0412)

Anderson, T.L., **D.J. Hocking**, C.A. Conner, J.E. Earl, E.B. Harper, M.S. Osbourn, W.E. Peterman, T.A.G. Rittenhouse, and R.D. Semlitsch. 2015. Abundance and phenology patterns of two pond-breeding salamanders determine species interactions in natural populations. Oecologia. 177(3):761-73. [http://dx.doi.org/10.1007/s00442-014-3151-z](http://dx.doi.org/10.1007/s00442-014-3151-z)

Drake, D.L, B.H. Ousterhout, C.D. Shulse, **D.J. Hocking**, W.E. Peterman, T.A. Anderson, K.L. Lohraff, C.A. Conner, E.H. Harper, J.R. Johnson, T.A.G. Rittenhouse, B.B. Rothermel, L.S. Eggert, and R.D. Semlitsch. 2015. Pond-breeding amphibian community composition in Missouri. American Midland Naturalist. 174:180-187.

**Hocking, D.J.** and K.J. Babbitt. 2014. Amphibian Contributions to Ecosystem Services. Herpetological Conservation and Biology. 9(1):1-17. [**OA**]

**Hocking, D.J.** and K.J. Babbitt. 2014. The role of red-backed salamanders on ecosystem functions. PLoS ONE 9(1):e86854. [http://dx.doi.org/10.1371/journal.pone.0086854](http://dx.doi.org/10.1371/journal.pone.0086854) [**OA**]

**Hocking, D.J.** 2013. Comparing the influence of ecology journals using citation metrics: making sense of a multitude of metrics. Ideas in Ecology & Evolution. 6(1): 55–65. [http://dx.doi.org/10.4033/iee.v6i1.4949](http://dx.doi.org/10.4033/iee.v6i1.4949) [**OA**]

**Hocking, D.J.**, S.A. Callaghan, K.J. Babbitt, and M. Yamasaki. 2013. Comparison of silvicultural and natural disturbance effects on terrestrial salamanders in northern hardwood forests. Biological Conservation. 167:194-202. [http://dx.doi.org/10.1016/j.biocon.2013.08.006](http://dx.doi.org/10.1016/j.biocon.2013.08.006)

**Hocking, D.J.**, G.M. Connette, C.A. Conner, B.R. Scheffers, S.E. Pittman, W.E. Peterman, R.D. Semlitsch. 2013. Effects of experimental forest management on a terrestrial, woodland salamander in Missouri. Forest Ecology and Management. 287:32-39

Osbourn, M.S., **D.J. Hocking**, C.A. Conner, W.E. Peterman, and R.D. Semlitsch. 2011. Use of fluorescent visible implant Alphanumeric tags to individually mark juvenile ambystomatid salamanders. Herpetological Review 42(1):43-46.

**Hocking, D.J.** 2010. *Hyla squirella* (squirrel treefrog) reproduction. Herpetological Review 41(1):64.

Semlitsch, R.D., S.M. Blomquist, A.J.K. Calhoun, J.W. Gibbons, J.P. Gibbs, G.J. Graeter, E.B. Harper, **D.J. Hocking**, M.L. Hunter, D.A. Patrick, T.A.G. Rittenhouse, B.B. Rothermel, and B.D. Todd. 2009. Effects of timber management on amphibian populations: understanding mechanisms from forest experiments. Bioscience 59(10):853-862. (Cover Photograph)

Scheffers, B., E.D. McDonald, **D.J. Hocking**, C.A. Conner, and R.D. Semlitsch. 2009. A comparison of two artificial cover objects for sampling amphibians and reptiles. Herpetological Review 40(4):419-421.

Babbitt K.J., M.J. Baber, D.L. Childers, and **D.J. Hocking**. 2009. The influence of agricultural upland habitat type on larval anuran assemblages in seasonally-inundated wetlands. Wetlands 29(1):294-301.

**Hocking, D.J.** and R.D. Semlitsch. 2008. Effects of clearcut logging on gray treefrog (Hyla versicolor) tadpole performance. Journal of Herpetology 42:689-698.

**Hocking, D.J.**, T.A.G. Rittenhouse, B.B. Rothermel, J.R. Johnson, C.A. Conner, E.B. Harper, and R.D. Semlitsch. 2008. Breeding and recruitment phenology of amphibians in Missouri oak-hickory forests. American Midland Naturalist 160:41-60.

Semlitsch, R.D., C.A. Conner, **D.J. Hocking**, T.A.G. Rittenhouse, and E.B. Harper. 2008. Effects of timber harvesting on pond-breeding amphibian persistence: testing the evacuation hypothesis. Ecological Applications 18(2):283-289.

**Hocking, D.J.** and R.D. Semlitsch. 2007. Effects of timber harvest on breeding site selection by gray treefrogs (Hyla versicolor). Biological Conservation 138:506-513.

# Grants 

## Submitted

National Park Service. Natural Resource Stewardship and Science FY19 Servicewide Comprehensive Call. Effects of wildfire on salamander populations in Great Smoky Mountains National Park. D.J. Hocking, J.A. Crawford, W.E. Peterman, and J.R. Milanovich. 2019 Pending Congressional Authorization. $76,464.

## Awarded (Total: $350,135)

Frostburg Foundation Opportunity Grant. Effects of acid mine drainage and stream restoration on Plethodontid salamanders. D.J. Hocking and J. Brooks\*. 2018. $1,329. 

Frostburg State University. Faculty Development Graduate Research Grant. Spatial patterns, home ranges, and associated parasites in the Chesapeake and Ohio Canal National Historic Park. D.J. Hocking and N. Haydt\*. 2018. $1,500.

Appalachian Highlands Science Learning Center Research Grants. Effects of Wildlife on Salamander Populations in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, and J.R. Milanovich. 2018. $2,000

Great Smoky Mountains Conservation Association. Carlos C. Campbell and James T. Tanner Memorial Fund. Short-term Effects of Wildlife on Salamander Populations in Great Moky Mountains National Park. D.J. Hocking, J.A. Crawford, W.E. Peterman, J.R. Milanovich. 2017. $5,000

Appalachian Highlands Science Learning Center Research Grants. Short-term Effects of Wildlife on Salamander Populations in Great Moky Mountains National Park. J.A. Crawford, D.J. Hocking, W.E. Peterman, J.R. Milanovich. 2017. $1,124

Frostburg State University. Faculty Development Undergraduate Research Grant. D.J. Hocking. 2017. $3,750.

Frostburg State University CLAS Strategic Plan Fund. Salamander population and adaptation research collaborative network. D.J. Hocking. 2017. $500

USGS Mendenhall Research Fellowship. Hierarchical modeling of climate change effects: Land-use impacts on brook trout population persistence. D.J. Hocking.2014-2016. $250,000

National Geographic Society. Waitt Grant. Climate change effects on elevational distributions of salamanders in Great Smoky Mountains National Park. J.A. Crawford, D.J. Hocking, J. Milanovich, W.E. Peterman. 2012. $14,932
 
NH Agricultural Experiment Station. McIntire-Stennis. The role of red-backed salamanders (*Plethodon cinereus*) in forest-floor ecosystem functions. D.J. Hocking, K.J. Babbitt. 2011. $42,000

University of New Hampshire. Dissertation Year Fellowship. The contributions of woodland salamanders to ecosystem functions. D.J. Hocking. 2011. $16,000

University of Missouri. Trans-World Airlines Scholarship. The effects of predators on gray treefrog (*Hyla versicolor*) growth, survival, and development. D.J. Hocking. 2006. $7,000

# Teaching

## Courses

* General Ecology (BIOL 340), Frostburg State University. 2016 - present. Spring, Fall.

* Herpetology (BIOL 422/522), Frostburg State University. 2017 - present. Spring.

* Quantitative Analysis of Vertebrate Populations (BIOL 414/514). 2017 - present. Fall.

* General Zoology Laboratory (BIOL 160). 2016 - present. Variable.

* Vertebrate Biology (NR 655), University of New Hampshire. 2009.

* Introduction to Conservation Biology (BIO 105), Moberly Area Community College, Columbia, MO. 2007.

## Teaching Assistant

* 2007, 2009  Wildlife Techniques (NR 646), University of New Hampshire

* 2008        Conservation Biology (NR 650), University of New Hampshire

## Tutor

* 2010        Introductory Biology (Bio 412), University of New Hampshire

* 2010        Freshwater Resources (NR 504), University of New Hampshire

* 2008-2010   Sociology Statistics (Soc 502), University of New Hampshire

* 2009        Contemporary Conservation Issues (NR 435), University of New Hampshire

## Environmental Education

* 2003-2004   Senior Environmental Intern. Audubon Maryland-DC.

* 2001-2003   Seasonal Naturalist. NH Seacoast Science Center. 

## Certifications

* Cognate in College Teaching, Center for Excellence in Teaching & Learning, University of New Hampshire

* Software Carpentry Instructor, Teaching Lab Skills for Scientific Computing [http://software-carpentry.org/](http://software-carpentry.org/) 

# Research Mentoring

## Graduate Students

* Natalie Haydt, Spatial capture-recapture and disease of turtles along a depth gradient in the C&O Canal. 2017 - present

* Jacey Brooks, The effects of Acid Mine Drainage and remediation on stream salamander populations. 2017 - present

* Bethany Liberto, Abundance and distribution of rare dragonflies in high elevation bogs. *Co-advised with Dr. Jered Studinski*. 2017 - present

## Graduate Student Committees

Ryan Stephens (PhD, University of New Hampshire, 2018); Sabrina Edwards (MS, Frostburg State University); Emily Harlan (MS, Frostburg State University); Erica Duda (MS, Frostburg State University); Elizabeth Green (MS, Frostburg State University)

## Undergraduate Researchers

I have mentored 14 undergraduate students (6 women, 8 men) on independent research projects, including multiple first generation college students and one U.S. Army Veteran. 

